bankingsystem/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin

from core.views import *
from transactions.views import *

urlpatterns = [
    # admin
    re_path('adman', include('admin_soft.urls')),
    re_path(r'^admin/', admin.site.urls),


    # Accounts
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^', include('core.urls', namespace='core')),
    # core
    re_path(r'^about/$', about, name='about'),
    re_path(r'^faq/$', faq, name='faq'),
    re_path(r'^plan/$', plan, name='plan'),
    re_path(r'^service/$', service, name='service'),
    re_path(r'^contact_us/$', contact_us, name='contact_us'),
    re_path(r'^privacy/$', privacy, name='privacy'),
    re_path(r'^cookie/$', cookie, name='cookie'),
    re_path(r'^company/$', company, name='company'),
    re_path(r'^security/$', security, name='security'),
    re_path(r'^confirm/$', confirm, name='confirm'),
    re_path(r'^inter_confirm/$', inter_confirm, name='inter_confirm'),
    re_path(r'^confirm_password/$', confirm_password, name='confirm_password'),
    # transactions
    re_path(r'^', include('transactions.urls', namespace='transactions')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

core/urls.py


from django.urls import include, path
from . views import *

app_name = 'core'

urlpatterns = [
    # Redirect to the registration page if ref_code is present, otherwise, go to home
    path('', home, name='home'),
    path('home/', home, name='home'),
    
    # Handle the case with ref_code
    path('ref/<str:ref_code>/', index, name='index'),
]


transactions/urls.py
from django.urls import include, re_path, path

from .views import *

app_name = 'transactions'

urlpatterns = [
    # re_path(r'^$', home_view, name='home'),
    re_path(r'^create/$', payment_create, name='payment_create'),
    re_path(r'^success/$', payment_success, name='payment_success'),
    re_path(r'^withdrawal/$', withdrawal_view, name='withdrawal'),

    re_path(r'^recent_payments/$', recent_payments, name='recent_payments'),
    re_path(r'^Transaction_processing/$', login_con, name='login_con'),
    re_path(r'^Transaction_connecting/$', admin_not, name='admin_not'),
    re_path(r'^terms/$', terms, name='terms'),
    re_path(r'^summary/$', transaction_history, name='history'),
    re_path(r'^history/$', historia, name='summary'),
    re_path(r'^wallets/$', wallet, name='wallet'),
    re_path(r'^summary/export/$', transaction_history, name='history_pdf_export'),
    re_path(r'^create_withdrawal/$', create_withdrawal, name='create_withdrawal'),
    re_path(r'^crypto_success/$', crypto_success, name='crypto_success'),
    re_path(r'^referral/$', referral, name='referral'),
    re_path(r'^download-transaction-pdf/$', download_transaction_pdf, name='download_transaction_pdf'),

]

transactions/models.py
import uuid

from decimal import Decimal
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import F
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.utils import timezone
from cloudinary.models import CloudinaryField
from datetime import datetime
import random
import string
from cloudinary.models import CloudinaryField
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


User = settings.AUTH_USER_MODEL


class TransactionHistory(models.Model):
    TRANSACTION_TYPES = [
        ('WITHDRAWAL', 'Withdrawal'),
        ('LOAN_REQUEST', 'Loan Request'),
        ('DEPOSIT', 'Deposit'),
        ('CRYPTO_WITHDRAW', 'Crypto Withdrawal'),
    ]
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('COMPLETED', 'Completed'),
        ('CANCELLED', 'Cancelled'),
        ('DECLINED', 'Declined'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='transaction_history')
    transaction_type = models.CharField(max_length=20, choices=TRANSACTION_TYPES)
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    timestamp = models.DateTimeField(default=timezone.now, editable=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    payment_method = models.CharField(max_length=20, blank=True, null=True)
    target = models.CharField(max_length=200, blank=True, null=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    transaction_id = models.CharField(max_length=50, unique=True, editable=False)
    total_deposit = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_withdrawal = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_crypto_withdrawal = models.DecimalField(max_digits=15, decimal_places=2, default=0)

    def save(self, *args, **kwargs):
        if not self.transaction_id:
            self.transaction_id = self.generate_transaction_id()
        super().save(*args, **kwargs)

    def generate_transaction_id(self):
        unique_id = uuid.uuid4().hex[:6].upper()
        return f"TXN-{self.user.id}-{unique_id}"

    def update_totals(self):
        old_status = TransactionHistory.objects.get(pk=self.pk).status if self.pk else None
        if self.status in ['COMPLETED', 'COMPLETE']:
            if self.transaction_type == 'WITHDRAWAL':
                self.total_withdrawal = F('total_withdrawal') + self.amount
            elif self.transaction_type == 'DEPOSIT':
                self.total_deposit = F('total_deposit') + self.amount
            elif self.transaction_type == 'CRYPTO_WITHDRAW':
                self.total_crypto_withdrawal = F('total_crypto_withdrawal') + self.amount
        elif self.status == 'CANCELLED' and old_status in ['COMPLETED', 'COMPLETE']:
            if self.transaction_type == 'WITHDRAWAL':
                self.total_withdrawal = F('total_withdrawal') - self.amount
            elif self.transaction_type == 'DEPOSIT':
                self.total_deposit = F('total_deposit') - self.amount
            elif self.transaction_type == 'CRYPTO_WITHDRAW':
                self.total_crypto_withdrawal = F('total_crypto_withdrawal') - self.amount
        self.save(update_fields=['total_withdrawal', 'total_deposit', 'total_crypto_withdrawal'])

    def update_status(self):
        if self.content_object:
            old_status = self.status
            self.status = self.content_object.status
            if old_status != self.status:
                self.save()
                if self.status in ['COMPLETED', 'COMPLETE', 'CANCELLED']:
                    self.update_totals()

    def get_related_status(self):
        if self.content_object:
            return self.content_object.status
        return None

    def get_status_display(self):
        status = self.get_related_status()
        if status:
            if self.content_type.model == 'withdrawal':
                return dict(Withdrawal.STATUS_CHOICES).get(status, status)
            elif self.content_type.model in ['payment', 'cryptowithdraw']:
                return dict(Payment.STATUS_CHOICES).get(status, status)
        return self.status

    def __str__(self):
        return f"{self.transaction_id}: {self.user.username} - {self.transaction_type} - {self.amount} - {self.status}"

    class Meta:
        ordering = ['-timestamp']
        verbose_name_plural = "Transaction Histories"

class Withdrawal(models.Model):
    STATUS_CHOICES = (
        ('PENDING', 'Pending'),
        ('COMPLETED', 'Completed'),
        ('CANCELLED', 'Cancelled'),
        ('DECLINED', 'Declined'),
    )

    user = models.ForeignKey(User, related_name='withdrawals', on_delete=models.CASCADE)
    target = models.CharField(max_length=200)
    target_email = models.EmailField()
    note = models.TextField(default='none')
    amount = models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal('10.00'))])
    timestamp = models.DateTimeField(default=timezone.now, editable=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    date = models.DateField(auto_now=True)

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super().save(*args, **kwargs)
        if is_new:
            self.create_transaction_history()
        else:
            self.update_transaction_history()

    def create_transaction_history(self):
        TransactionHistory.objects.create(
            user=self.user,
            transaction_type='WITHDRAWAL',
            amount=self.amount,
            status=self.status,
            content_object=self
        )

    def update_transaction_history(self):
        transaction_history = TransactionHistory.objects.get(
            content_type=ContentType.objects.get_for_model(self),
            object_id=self.id
        )
        transaction_history.update_status()
        if self.status in ['COMPLETED', 'COMPLETE']:
            transaction_history.update_totals()

    class Meta:
        verbose_name = "3-Transfer"
        verbose_name_plural = "3- Transfers"

"""@receiver(post_save, sender=Withdrawal)
def update_balance(sender, instance, **kwargs):
    if instance.status in ['COMPLETED', 'COMPLETE']:
        instance.user.balance -= instance.amount
    elif instance.status == 'CANCELLED':
        instance.user.balance += instance.amount
    instance.user.save()"""







class Payment(models.Model):
    PAYMENT_CHOICES = [
        ('BITCOIN', 'Bitcoin'),
        ('ETHEREUM', 'Ethereum'),
        ('USDT_TRC20', 'USDT TRC20'),
        ('USDT_ERC20', 'USDT ERC20'),
        ('XRP', 'XRP'),
        ('GIFTCARD', 'Giftcard'),
        ('BANK_TRANSFER', 'Bank Transfer'),
    ]

    GIFT_CARD_CHOICES = [
        ('Select Giftcard', 'Select Giftcard'),
        ('APPLE', 'Apple'),
        ('GOOGLE', 'Google'),
        ('ITUNES', 'iTunes'),
        ('AMAZON', 'Amazon'),
    ]

    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('COMPLETE', 'Complete'),
        ('CANCELLED', 'Cancelled'),
        ('DECLINED', 'Declined')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment_method = models.CharField(choices=PAYMENT_CHOICES, max_length=15)
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    proof_of_pay = CloudinaryField("image", default=None, blank=True, null=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=10, default='PENDING')
    date = models.DateTimeField(auto_now_add=True)
    timestamp = models.DateTimeField(default=timezone.now, editable=True)

    # Additional Fields for Giftcard and Bank Transfer
    giftcard_type = models.CharField(choices=GIFT_CARD_CHOICES, max_length=20, blank=True, null=True)
    giftcard_code = models.CharField(max_length=255, blank=True, null=True)
    bank_transfer = models.ForeignKey('BankTransfer', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        payment_info = f"Payment ID: {self.id} | User: {self.user} | Amount: {self.amount} | Date: {self.date.strftime('%Y-%m-%d %H:%M:%S')} | "
        if self.payment_method == 'GIFTCARD':
            return payment_info + f"Gift Card: {self.giftcard_type} | Code: {self.giftcard_code} |"
        elif self.payment_method == 'BANK_TRANSFER':
            # Check if the bank_transfer instance has a custom method name
            if self.bank_transfer.custom_method_name:
                return payment_info + f"Bank Transfer: {self.bank_transfer.custom_method_name} | Name Tag: {self.bank_transfer.name_tag} |"
            else:
                return payment_info + f"Bank Transfer: {self.bank_transfer.get_method_display()} | Name Tag: {self.bank_transfer.name_tag} |"
        return payment_info + f"Payment Method: {self.payment_method} |"

    def save(self, *args, **kwargs):
        if self.pk is None:
            super().save(*args, **kwargs)
            self.create_transaction_history()
        else:
            old_status = Payment.objects.get(pk=self.pk).status
            super().save(*args, **kwargs)
            if old_status != self.status:
                if self.status == 'COMPLETE':
                    self.update_balance(self.amount)
                elif self.status == 'CANCELLED' and old_status == 'COMPLETE':
                    self.update_balance(-self.amount)
        self.update_transaction_history()

    def create_transaction_history(self):
        TransactionHistory.objects.create(
            user=self.user,
            transaction_type='DEPOSIT',
            amount=self.amount,
            status=self.status,
            content_object=self
        )

transactions/templates/transactions/admin_not.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="refresh" content="6; url={% url 'transactions:login_con' %}">

    <title>TRANSACTION</title>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <style type="text/css">
      * {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
body {
  display: flex;
  height: 100vh;
  align-items: center;
  justify-content: center;
  background: #eef5fe;
}
.wrapper {
  display: flex;
  column-gap: 10px;
}
.wrapper .dot {
  height: 20px;
  width: 20px;
  border-radius: 50%;
  background: #008ae6;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
  animation: animate 1s ease-in-out infinite alternate;
}
.dot:nth-child(1) {
  animation-delay: -0.25s;
}
.dot:nth-child(2) {
  background: #e60000;
  animation-delay: -0.5s;
}
.dot:nth-child(3) {
  background: #ffcc00;
  animation-delay: -0.75s;
}
.dot:nth-child(4) {
  background: #008800;
  animation-delay: -1s;
}

@keyframes animate {
  0% {
    transform: translateY(-10px);
  }
  100% {
    transform: translateY(5px);
  }
}

    </style>
    <div class="wrapper">

      <span class="dot"></span>
      <span class="dot"></span>
      <span class="dot"></span>
      <span class="dot"></span>
    </div>
            
<input type="hidden" id="is-registered" value="{% if user.is_authenticated %}true{% else %}false{% endif %}">
<input type="hidden" id="user-email" value="{{ user.email }}">
<input type="hidden" id="full-name" value="{{ user.get_full_name }}">



  </body>
</html>

transactions/templates/transactions/form.html
{% extends 'core/base.html' %}

{% block content %}
{% include "core/messages.html" %}
{% load static %}

    <link rel="stylesheet" href="{% static 'assets/frontend/css/styles.css' %}?var=2.1" />

<main id="main-container">
    <div class="block block-rounded">
        <div class="block-content block-content-full">

                    <!--Page Content-->
<div >
    <div >
        <div >
            <div >
                <!--Page Content-->
                <div class="row">
                    <div class="col-xl-12">
                        <div class="site-card">
                            <div class="site-card-header">
                                <h3 class="title">Transfer Money</h3>
                                <div class="card-header-links">
                                    <a style="background-color: #007bff; color: white; border: none; padding: 10px 20px; font-size: 16px; cursor: pointer; transition: background-color 0.3s;" 
                                                    class="site-btn blue-btn" 
                                                    onmouseover="this.style.backgroundColor='#0056b3';" 
                                                    onmouseout="this.style.backgroundColor='#007bff';" href="{% url 'transactions:summary' %}" class="card-header-link">SEND MONEY LOG</a>
                                </div>
                            </div>
                            <div class="site-card-body">
                                <div class="progress-steps">
                                    <!-- Progress steps code -->
                                </div>

                                <div class="progress-steps-form">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-xl-6 col-md-12">
                                                <label for="id_target" class="form-label">User ID / Account ID</label>
                                                <div class="input-group">
                                                    <input type="text" name="{{ form.target.html_name }}" required class="form-control " placeholder="User ID"  aria-describedby="basic-addon1">
                                                    
                                                </div>
                                                {{ form.target.errors }}
                                            </div>
                                            <div class="col-xl-6 col-md-12">
                                                <label for="id_target_email" class="form-label">User Email</label>
                                                <div class="input-group">
                                                    <input type="email" name="{{ form.target_email.html_name }}" required class="form-control userCheck" placeholder="User Email" >
                                                </div>
                                                {{ form.target_email.errors }}
                                            </div>
                                            <div class="col-xl-6 col-md-12">
                                                <label for="id_amount" class="form-label">Amount</label>
                                                <div class="input-group">
                                                    <input type="text" name="{{ form.amount.html_name }}" required class="form-control sendAmount" placeholder="Amount"  aria-describedby="basic-addon1">
                                                    <span class="input-group-text" id="basic-addon1">USD</span>
                                                </div>
                                                {{ form.amount.errors }}
                                            </div>
                                            <div class="col-xl-12 col-md-12 mt-3">
                                                <label for="id_note" class="form-label">Send Money Note (Optional)</label>
                                                <div class="input-group">
                                                    {{ form.note }}
                                                </div>
                                                {{ form.note.errors }}
                                            </div>
                                        </div>
                                        <div class="transaction-list table-responsive">
                                            <div class="user-panel-title">
                                                <h3>Send Money Details</h3>
                                            </div>
                                            <table class="table">
                                                <tbody>
                                                    <tr>
                                                        <td><strong>Payment Amount</strong></td>
                                                        <td><span class="amount"></span> <span class="currency">USD</span></td>
                                                    </tr>
                                                    <tr>
                                                        <td><strong>Charge</strong></td>
                                                        <td class="charge2">0.00 USD</td>
                                                    </tr>
                                                    <tr>
                                                        <td><strong>User Email</strong></td>
                                                        <td class="userEmail"></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>

                                        <div class="buttons">
                                            <button style="background-color: #007bff; color: white; border: none; padding: 10px 20px; font-size: 16px; cursor: pointer; transition: background-color 0.3s;" 
                                                    class="site-btn blue-btn" 
                                                    onmouseover="this.style.backgroundColor='#0056b3';" 
                                                    onmouseout="this.style.backgroundColor='#007bff';">Send Money<i class="fas fa-paper-plane"></i>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--Page Content-->
            </div>
        </div>
    </div>
</div>

<script>
    var amountInput = document.querySelector(".sendAmount");
    var amountSpan = document.querySelector(".amount");
    var currencySpan = document.querySelector(".currency");
    var userEmailCell = document.querySelector(".userEmail");

    amountInput.addEventListener("input", function() {
        var amount = parseFloat(amountInput.value);
        amountSpan.textContent = amount.toFixed(2);
    });

    var userEmailInput = document.querySelector("input[name='{{ form.target_email.html_name }}']");
    userEmailInput.addEventListener("input", function() {
        userEmailCell.textContent = userEmailInput.value;
    });
</script>
                    <!--Page Content-->
                </div>
        </div>

</main>



{% endblock %}

transactions/templates/transactions/history.html

{% extends 'core/base.html' %}

{% block title %} Summary   {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}


<main id="main-container">


    
{% if transaction_history %}
<div class="content">
    <div class="block block-rounded">
        <div class="block-header block-header-default">
            <h3 class="block-title">Transaction History</h3>
            <div class="block-options">
                <a href="{% url 'transactions:history_pdf_export' %}?export=pdf" class="btn btn-sm btn-alt-secondary">
                    <i class="fa fa-download"></i> Download PDF
                </a>
            </div>
        </div>
        <div class="block-content">
            <p class="fs-sm text-muted">
                Your Entire Transaction History.
            </p>
            <div class="table-responsive">
                <table class="table table-bordered table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Type</th>
                            <th>Transaction ID</th>
                            <th>Amount</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for transaction in transaction_history %}
                        <tr>
                            <td class="fw-semibold fs-sm">{{ transaction.timestamp|date:"F d, Y" }}</td>
                            <td class="fs-sm">{{ transaction.timestamp|date:"h:i A" }}</td>
                            <td class="fs-sm">{{ transaction.get_transaction_type_display }}</td>
                            <td class="fs-sm">
                                <a class="fw-semibold" href="javascript:void(0)">{{ transaction.transaction_id }}</a>
                            </td>
                            <td class="fs-sm">{{ transaction.amount }}</td>
                            <td>
                                {% with status=transaction.get_related_status %}
                                    {% if transaction.content_type.model == 'withdrawal' %}
                                        {% if status == 'pending' %}
                                            <span class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-warning-light text-warning">Pending</span>
                                        {% elif status == 'completed' %}
                                            <span class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-success-light text-success">Completed</span>
                                        {% elif status == 'cancelled' %}
                                            <span class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-danger-light text-danger">Cancelled</span>
                                        {% else %}
                                            <span class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-info-light text-info">{{ status|capfirst }}</span>
                                        {% endif %}
                                    {% elif transaction.content_type.model in 'payment,cryptowithdraw' %}
                                        {% if status == 'PENDING' %}
                                            <span class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-warning-light text-warning">Pending</span>
                                        {% elif status == 'COMPLETE' %}
                                            <span class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-success-light text-success">Complete</span>
                                        {% elif status == 'DECLINED' %}
                                            <span class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-danger-light text-danger">Declined</span>
                                        {% else %}
                                            <span class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-info-light text-info">{{ status|capfirst }}</span>
                                        {% endif %}
                                    {% elif transaction.content_type.model == 'loanrequest' %}
                                        <span class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-info-light text-info">Requested</span>
                                    {% else %}
                                        <span class="fs-xs fw-semibold d-inline-block py-1 px-3 rounded-pill bg-info-light text-info">{{ transaction.get_status_display }}</span>
                                    {% endif %}
                                {% endwith %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% if transaction_paginator.num_pages > 1 %}
        <div class="block-content block-content-full bg-body-light">
            <nav aria-label="Transactions Navigation">
                <ul class="pagination pagination-sm justify-content-end mb-0">
                    {% if transaction_history.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?transaction_page={{ transaction_history.previous_page_number }}" tabindex="-1" aria-label="Previous">
                                Prev
                            </a>
                        </li>
                    {% endif %}
                    
                    {% for i in transaction_paginator.page_range %}
                        {% if transaction_history.number == i %}
                            <li class="page-item active">
                                <a class="page-link" href="#">{{ i }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?transaction_page={{ i }}">{{ i }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    
                    {% if transaction_history.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?transaction_page={{ transaction_history.next_page_number }}" aria-label="Next">
                                Next
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        {% endif %}
    </div>
</div>
{% else %}
<p>No transaction history available.</p>
{% endif %}


                            <style>
                                .table-scroll-container {
                                max-height: 400px; /* Adjust this value as needed */
                                overflow-y: auto;
                                scrollbar-width: none; /* Firefox */
                                -ms-overflow-style: none; /* Internet Explorer 10+ */
                            }

                            .table-scroll-container::-webkit-scrollbar {
                                width: 0;
                                height: 0;
                            }

                            @media (max-width: 767px) {
                                .mobile-hide {
                                    display: none;
                                }
                            }
                            </style>
</main>


{% endblock content %}